-- Add X/Twitter engagement tracking to products
ALTER TABLE products ADD COLUMN IF NOT EXISTS x_post_url TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS x_likes INTEGER NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS x_reposts INTEGER NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS x_replies INTEGER NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS x_views INTEGER NOT NULL DEFAULT 0;
